### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Septias** [deltachat/webxdc_website#1]
You add your feedback here :)

**Comment by missytake** [comment]
A few things I observed:
 
- if we want to go with webxdc, we should find a consensus about upper/lowercase spelling. I would go all lowercase for now. ownCloud struggled for years (and is still struggling) to get everyone to write it "ownCloud".
- the title of the page is still Vitesse
- the video doesn't show webxdc, only sending a DC message to a non-DC-client
- the page still talks of apps instead of interactive content

**Comment by r10s** [comment]
these points are all targeted, right? let's open separate issues for futher points.
